### ISSUE TITLE
Not FUD?

### ISSUE THREAD

**Issue by ricko2991** [PushpenderIndia/crypter#6]
is there a way to make it undetectable by antivirus ?. because I've tried it and always detected antivirus like windows defender as in my case.

**Comment by PushpenderIndia** [comment]
I have not tested this crypter for a long time, so there are chances that
AVs are now finded a way to detect payloads encrypted with this python
crypter.

Crypter methods do not last forever, you have to do hit and trail, and open
source projects quickly get detectable by AVs because there source code is
publically disclosed

**Comment by ricko2991** [comment]
Thanks for your answers, maybe I should dig deeper into the code and modify its contents, such as encrypting in other ways to bypass the antivirus. This is still a great tool, and shows how to obfuscate the payload.
